"""Local scaffolding generators: launcher .bat files, project directory
layouts, SuperTool / panel / Python tool skeletons.

These run on the machine hosting the MCP server (no Katana connection
required) and write files to disk.
"""

import os
import re
import stat
import textwrap


def _sanitize_name(name):
    cleaned = re.sub(r"[^0-9A-Za-z_]+", "_", name).strip("_")
    if not cleaned:
        raise ValueError("Name %r has no usable characters" % name)
    if cleaned[0].isdigit():
        cleaned = "_" + cleaned
    return cleaned


def _write(path, content):
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(textwrap.dedent(content).lstrip("\n"))
    return os.path.abspath(path)


# ---------------------------------------------------------------------------
# launcher .bat
# ---------------------------------------------------------------------------

def create_launcher_bat(katana_exe, output_path, project_path=None,
                        env_vars=None, katana_resources=None,
                        mcp_autostart=True, mcp_port=17820,
                        extra_args=None):
    """Write a Windows .bat that sets up the environment and starts Katana.

    katana_exe:      path to katanaBin.exe / katana.exe
    output_path:     where to write the .bat
    project_path:    optional .katana file to open
    env_vars:        dict of extra environment variables
    katana_resources: list of directories joined into KATANA_RESOURCES
    mcp_autostart:   add KATANA_MCP_AUTOSTART=1 so the bridge starts itself
    mcp_port:        KATANA_MCP_PORT value
    extra_args:      extra command line args appended to the Katana call
    """
    env_vars = dict(env_vars or {})
    if mcp_autostart:
        env_vars.setdefault("KATANA_MCP_AUTOSTART", "1")
        env_vars.setdefault("KATANA_MCP_PORT", str(mcp_port))

    lines = ["@echo off",
             "rem Generated by katana-mcp",
             "rem Launches Foundry Katana with a project environment.",
             ""]

    resources = list(katana_resources or [])
    if resources:
        joined = ";".join(resources)
        lines.append('set "KATANA_RESOURCES=%s;%%KATANA_RESOURCES%%"' % joined)

    for key in sorted(env_vars):
        lines.append('set "%s=%s"' % (key, env_vars[key]))

    cmd = '"%s"' % katana_exe
    if project_path:
        cmd += ' "%s"' % project_path
    if extra_args:
        cmd += " " + extra_args

    lines += ["", 'echo Starting Katana...', 'start "Katana" ' + cmd, ""]
    path = _write(output_path, "\r\n".join(lines) + "\r\n")
    return {"ok": True, "path": path,
            "preview": "\n".join(lines)}


# ---------------------------------------------------------------------------
# project directory scaffold
# ---------------------------------------------------------------------------

_DEFAULT_LAYOUT = [
    "assets/models",
    "assets/textures",
    "assets/hdri",
    "assets/plates",
    "assets/cameras",
    "lookdev",
    "lighting",
    "lighting/templates",
    "renders",
    "comp",
    "scripts",
    "refs",
    "docs",
]


def scaffold_project_directory(base_path, layout=None, extra_dirs=None):
    """Create a VFX project directory tree. Returns the created paths."""
    dirs = list(layout or _DEFAULT_LAYOUT)
    dirs += list(extra_dirs or [])
    created = []
    for rel in dirs:
        path = os.path.join(base_path, rel)
        os.makedirs(path, exist_ok=True)
        created.append(os.path.abspath(path))
    return {"ok": True, "base": os.path.abspath(base_path),
            "created": created, "count": len(created)}


# ---------------------------------------------------------------------------
# SuperTool skeleton
# ---------------------------------------------------------------------------

_SUPERTOOL_INIT = '''\
from .Node import {cls}
'''

_SUPERTOOL_NODE = '''\
"""SuperTool node definition for {name}.

Place the parent directory (the one containing the SuperTools folder) on
KATANA_RESOURCES, restart Katana, and the node type "{name}" becomes
available in the Tab menu.
"""

import PackageSuperToolAPI

from . import Editor


class {cls}(PackageSuperToolAPI.V2.Node):
    def __init__(self):
        super({cls}, self).__init__()
        self.addInputPort("in")
        self.addOutputPort("out")

        params = self.getParameters()
        params.createChildString("exampleParam", "default value")
        params.createChildNumber("exampleNumber", 1.0)

    def getEditor(self):
        return Editor.{cls}Editor(self)

    def apply(self, searchPattern="/root"):
        """Cook-time logic: modify the scene below searchPattern here."""
        pass
'''

_SUPERTOOL_EDITOR = '''\
"""Qt editor widget for the {name} SuperTool."""

try:
    from PySide6 import QtWidgets
except ImportError:
    from PySide2 import QtWidgets


class {cls}Editor(QtWidgets.QWidget):
    def __init__(self, node, parent=None):
        super({cls}Editor, self).__init__(parent)
        self._node = node

        layout = QtWidgets.QVBoxLayout(self)
        self._label = QtWidgets.QLabel("{name} - edit me in Editor.py")
        self._text = QtWidgets.QLineEdit()
        self._text.setPlaceholderText("exampleParam")
        self._text.editingFinished.connect(self._apply)

        current = node.getParameter("exampleParam")
        if current is not None:
            self._text.setText(str(current.getValue(0)))

        layout.addWidget(self._label)
        layout.addWidget(self._text)

    def _apply(self):
        param = self._node.getParameter("exampleParam")
        if param is not None:
            param.setValue(self._text.text(), 0)
'''


def scaffold_supertool(name, base_directory):
    """Create a PackageSuperToolAPI-based SuperTool skeleton under
    <base_directory>/SuperTools/<name>/. Add <base_directory> to
    KATANA_RESOURCES to load it."""
    cls = _sanitize_name(name)
    root = os.path.join(base_directory, "SuperTools", cls)
    files = {
        os.path.join(root, "__init__.py"): _SUPERTOOL_INIT.format(cls=cls),
        os.path.join(root, "Node.py"): _SUPERTOOL_NODE.format(name=cls,
                                                              cls=cls),
        os.path.join(root, "Editor.py"): _SUPERTOOL_EDITOR.format(name=cls,
                                                                  cls=cls),
    }
    written = [_write(p, c) for p, c in files.items()]
    return {"ok": True, "directory": os.path.abspath(root),
            "files": written,
            "activate": ("Add %r to KATANA_RESOURCES and restart Katana; "
                         "the node type %r appears in the Tab menu."
                         % (os.path.abspath(base_directory), cls))}


# ---------------------------------------------------------------------------
# panel (tab) tool skeleton
# ---------------------------------------------------------------------------

_PANEL_TEMPLATE = '''\
"""Katana tab: {name}

Katana discovers this file when its parent "Tabs" directory lives under a
KATANA_RESOURCES path. Open it via Tabs > {name}.
"""

try:
    from PySide6 import QtWidgets
except ImportError:
    from PySide2 import QtWidgets

from Katana import UI4


class {cls}Panel(UI4.Tabs.BaseTab):
    def __init__(self, parent):
        super({cls}Panel, self).__init__(parent)
        layout = QtWidgets.QVBoxLayout(self)
        layout.addWidget(QtWidgets.QLabel("{name} panel - build me!"))
        self._button = QtWidgets.QPushButton("Do something")
        self._button.clicked.connect(self._on_click)
        layout.addWidget(self._button)
        layout.addStretch(1)

    def _on_click(self):
        from Katana import NodegraphAPI
        root = NodegraphAPI.GetRootNode()
        print("{name}: root has %d children" % len(root.getChildren()))


PluginRegistry = [("KatanaPanel", 2, "{name}", {cls}Panel)]
'''


def scaffold_panel_tool(name, base_directory):
    """Create a Katana panel (tab) skeleton under <base_directory>/Tabs/."""
    cls = _sanitize_name(name)
    path = os.path.join(base_directory, "Tabs", cls + ".py")
    written = _write(path, _PANEL_TEMPLATE.format(name=cls, cls=cls))
    return {"ok": True, "file": written,
            "activate": ("Add %r to KATANA_RESOURCES and restart Katana; "
                         "open via Tabs > %s."
                         % (os.path.abspath(base_directory), cls))}


# ---------------------------------------------------------------------------
# python tool skeleton
# ---------------------------------------------------------------------------

_STARTUP_TOOL = '''\
"""Katana startup script: {name}

Lives in a "Startup" directory under a KATANA_RESOURCES path; runs once
when Katana launches.
"""


def register():
    from Katana import UI4
    mw = UI4.App.MainWindow.GetMainWindow()
    try:
        menubar = mw.menuBar()
    except AttributeError:
        return
    menu = menubar.addMenu("{name}")
    action = menu.addAction("Run {name}")
    action.triggered.connect(run)


def run():
    from Katana import NodegraphAPI
    root = NodegraphAPI.GetRootNode()
    print("{name} ran: %d root-level nodes" % len(root.getChildren()))


register()
'''

_SHELF_TOOL = '''\
"""Katana shelf / script tool: {name}

Run from Katana's Python shelf, or bind it to a menu with the Startup
scaffold. Keep logic in run() so it stays testable.
"""


def run():
    from Katana import NodegraphAPI

    selected = NodegraphAPI.GetAllSelectedNodes()
    if not selected:
        print("{name}: select at least one node first")
        return

    for node in selected:
        print("{name}: %s (%s)" % (node.getName(), node.getType()))
        # TODO: do the actual work here


if __name__ == "__main__":
    run()
'''


def scaffold_python_tool(name, base_directory, kind="startup"):
    """Create a Python tool skeleton. kind='startup' writes
    <base>/Startup/<name>.py (auto-registered menu). kind='shelf' writes
    <base>/Scripts/<name>.py (importable shelf/script tool)."""
    cls = _sanitize_name(name)
    if kind == "startup":
        path = os.path.join(base_directory, "Startup", cls + ".py")
        template = _STARTUP_TOOL
        activate = ("Add %r to KATANA_RESOURCES and restart Katana; a %r "
                    "menu appears." % (os.path.abspath(base_directory), cls))
    else:
        path = os.path.join(base_directory, "Scripts", cls + ".py")
        template = _SHELF_TOOL
        activate = ("Run inside Katana: import %s; %s.run()" % (cls, cls))
    written = _write(path, template.format(name=cls))
    return {"ok": True, "file": written, "activate": activate}


# ---------------------------------------------------------------------------
# template store (local JSON files)
# ---------------------------------------------------------------------------

def default_templates_dir():
    return os.environ.get(
        "KATANA_MCP_TEMPLATES_DIR",
        os.path.join(os.path.expanduser("~"), ".katana-mcp", "templates"))


def template_path(name, directory=None):
    safe = _sanitize_name(name)
    return os.path.join(directory or default_templates_dir(),
                        safe + ".json")
